import { BASE_PATH } from "./basePath";

/**
 * The bundled sample statement: synthetic data generated by
 * scripts/sample-statement/make.mjs. Keep the password in sync with
 * SAMPLE_PASSWORD in scripts/sample-statement/data.mjs (a test checks this).
 */
export const SAMPLE_URL = `${BASE_PATH}/sample/sample-statement.pdf`;
export const SAMPLE_PASSWORD = "01000000000";
